import vertexclass
import disease
def main():
    A = vertexclass.Vertex("A",disease.Disease(3,.45,.1))
    B = vertexclass.Vertex("B",disease.Disease(3,.45,.1))
    C = vertexclass.Vertex("C",disease.Disease(3,.45,.1))
    D = vertexclass.Vertex("D",disease.Disease(3,.45,.1))
    E = vertexclass.Vertex("E",disease.Disease(3,.45,.1))
    F = vertexclass.Vertex("F",disease.Disease(3,.45,.1))
    G = vertexclass.Vertex("G",disease.Disease(3,.45,.1))
    H = vertexclass.Vertex("H",disease.Disease(3,.45,.1))
    I = vertexclass.Vertex("I",disease.Disease(3,.45,.1))
    A.addNeighbor(B)
    A.addNeighbor(C)
    B.addNeighbor(D)
    B.addNeighbor(G)
    C.addNeighbor(E)
    C.addNeighbor(F)
    D.addNeighbor(F)
    E.addNeighbor(H)
    F.addNeighbor(H)
    F.addNeighbor(I)
    H.addNeighbor(I)
    A.setStatus('I')
    C.setStatus('I')
    E.setStatus('I')
    print(A.getConnections())
main()